### ISSUE TITLE
TypeError: get() got an unexpected keyword argument 'fallback'

### ISSUE THREAD

**Issue by gbmhunter** [SchrodingersGat/KiBoM#124]
I am using the latest version of `KiBoM` (`master` branch as of today) with KiCAD `v5.1.6` on Ubuntu 18.04.

I am invoking `KiBoM` using the KiCAD GUI. The first time (when no `bom.ini` is present) it works fine. However when I click `Generate` a second time it fails with the following error (I have made no `bom.ini` modifications):

```
Error messages:
Traceback (most recent call last):
  File "/home/ghunter/repos/kibom/KiBOM_CLI.py", line 28, in <module>
    main()
  File "/home/ghunter/repos/kibom/kibom/__main__.py", line 175, in main
    pref.Read(config_file)
  File "/home/ghunter/repos/kibom/kibom/preferences.py", line 147, in Read
    fallback=self.outputFileName)
TypeError: get() got an unexpected keyword argument 'fallback'
```

**Comment by gbmhunter** [comment]
Woops, I traced this problem to the fact that my system `python` was symlinked to `python2` and not `python3`. Calling `python3` fixed this.
