### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by wmsmtvideo** [SchrodingersGat/KiBoM#40]
Even with a schematic that has only a single resistor from the standard library I get the following error.
KiCad is version 4.0.7 running under Windows 10, with the KiBOM version I downloaded on 30th August 2018.

Did I miss something or is this a real bug?

Thanks for the help

KiBOM Output from Bill of Material Window in KiCad
```
Run command:
python "C:/_owncloud/Documents/KiCad/KiBoM-master/KiBOM_CLI.py" "C:/_owncloud/Documents/KiCad/_dummy2/dummy.xml" "C:/_owncloud/Documents/KiCad/_dummy2/dummy"

Command error. Return code 1

Error messages:
Traceback (most recent call last):
  File "C:/_owncloud/Documents/KiCad/KiBoM-master/KiBOM_CLI.py", line 124, in <module>
    groups = net.groupComponents(components)
  File "C:/_owncloud/Documents/KiCad/KiBoM-master/bomlib/netlist_reader.py", line 422, in groupComponents
    g.updateFields(self.prefs.useAlt, self.prefs.altWrap)
  File "C:/_owncloud/Documents/KiCad/KiBoM-master/bomlib/component.py", line 471, in updateFields
    self.fields[ColumnList.COL_DESCRIPTION] = self.components[0].getDescription()
  File "C:/_owncloud/Documents/KiCad/KiBoM-master/bomlib/component.py", line 127, in getDescription
    return self.element.get("libsource", "description")
  File "C:/_owncloud/Documents/KiCad/KiBoM-master/bomlib/netlist_reader.py", line 190, in get
    ret = child.get(elemName, attribute, attrmatch)
  File "C:/_owncloud/Documents/KiCad/KiBoM-master/bomlib/netlist_reader.py", line 183, in get
    return self.attributes[attribute]
KeyError: 'description'

```

And here the xml file

```
<?xml version="1.0" encoding="UTF-8"?>
<export version="D">
  <design>
    <source>C:/_owncloud/Documents/KiCad/_dummy2/dummy.sch</source>
    <date>31/08/2018 08:43:49</date>
    <tool>Eeschema 4.0.7</tool>
    <sheet number="1" name="/" tstamps="/">
      <title_block>
        <title/>
        <company/>
        <rev/>
        <date/>
        <source>dummy.sch</source>
        <comment number="1" value=""/>
        <comment number="2" value=""/>
        <comment number="3" value=""/>
        <comment number="4" value=""/>
      </title_block>
    </sheet>
  </design>
  <components>
    <comp ref="R2">
      <value>330R</value>
      <footprint>Resistors_SMD:R_1206</footprint>
      <libsource lib="device" part="R"/>
      <sheetpath names="/" tstamps="/"/>
      <tstamp>5B88D4F0</tstamp>
    </comp>
  </components>
  <libparts>
    <libpart lib="device" part="R">
      <description>Resistor</description>
      <footprints>
        <fp>R_*</fp>
        <fp>R_*</fp>
      </footprints>
      <fields>
        <field name="Reference">R</field>
        <field name="Value">R</field>
      </fields>
      <pins>
        <pin num="1" name="~" type="passive"/>
        <pin num="2" name="~" type="passive"/>
      </pins>
    </libpart>
  </libparts>
  <libraries>
    <library logical="device">
      <uri>C:\Program Files\KiCad\share\kicad\library\device.lib</uri>
    </library>
  </libraries>
  <nets>
    <net code="1" name="Net-(R2-Pad1)">
      <node ref="R2" pin="1"/>
      <node ref="R2" pin="2"/>
    </net>
  </nets>
</export>

```

**Comment by SchrodingersGat** [comment]
Probably the fact that you are using an older version of KiCad. The new version (v5.x) broke some compatibility with KiBOM so it was updated to match.

I have made some changes which (hopefully) return compatibility with v4.x - can you re-download and test them? I do not have v4.x installed.

Let me know :)
